### ISSUE TITLE
EFI image update doesn't work

### ISSUE THREAD

**Issue by olddesklamp** [Ataraxxia/secure-arch#3]
Currently on basic installation.

I've followed this guide closely, but for some reason when I run `pacman -S linux` to update the EFI image I see this instead of the expected verbose output:

```
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating module dependencies...
(3/3) Updating Linux EFI image
dracut: Cannot find module directory /lib/modules/{kver%'/pkgbase'}/
dracut: and --no-kernel was not specified
error: command failed to execute correctly
```

**Comment by Ataraxxia** [comment]
You must be having some sort of typo in the `/usr/local/bin/dracut-install.sh` script
