### ISSUE TITLE
BTRFS

### ISSUE THREAD

**Issue by sallymanda** [Ataraxxia/secure-arch#6]
Hey :-) Gunna try out your guides this week, but I'm gunna see if I can get it working with btrfs, setup for timeshift, do I need to mess around with any of the instructions if its just a single encrypted partition with two subvolumes?

**Comment by Ataraxxia** [comment]
It works, just ctrl+f "ext4", replace with btrfs

**Comment by sallymanda** [comment]
> It works, just ctrl+f "ext4", replace with btrfs

Oh, I meant with an @ and @home subvolume layout, which is the only layout that timeshift accepts, but I'm just thinking maybe I'll switch over to snapper, it looks like it really is a better project, especially with the assistant gui. Just wish there were an option for incremental snapshots as well.
