### ISSUE TITLE
Installation error during kernel update

### ISSUE THREAD

**Issue by flokosoft** [Ataraxxia/secure-arch#7]
Since kernel 6.7.x, signing is no longer possible. The process is aborted with an error. Even after a new installation, if a kernel update is available. Where is the error? Thanks for your great work!

[kernel.txt](https://github.com/Ataraxxia/secure-arch/files/14121079/kernel.txt)

**Comment by Ataraxxia** [comment]
I am really late to this i guess, but two things I can see:

1.  You don't seem to have zstd installed, but it actually falls back to gzip
2.  Your signing key cannot be opened and thus it fails:

`Can't load certificate from file '/usr/share/secureboot/keys/db/db.pem`
