### ISSUE TITLE
failed to mount /sysroot

### ISSUE THREAD

**Issue by battlemag3** [Ataraxxia/secure-arch#9]
Filesystem check is passed on /dev/mapper/vg-root, then it fails to mount and drops me into maintenance shell, where I can mount it myself all good (mount /dev/mapper/vg-root /sysroot)
I have this from rdsoreport.txt
`
[   26.240304] archlinux mount[1165]: mount: /sysroot: fsconfig system call failed: ext4: Unknown parameter 'realtime'.

[   26.240304] archlinux mount[1165]:        dmesg(1) may have more information after failed mount system call.

[   26.240891] archlinux systemd[1]: sysroot.mount: Mount process exited, code=exited, status=32/n/a
`

**Comment by Ataraxxia** [comment]
I think it's just the typo, 'relatime', not realtime

sob., 28 wrz 2024, 06:21 użytkownik Michael ***@***.***>
napisał:

**Comment by battlemag3** [comment]
Wait, lol. Lemme check

**Comment by battlemag3** [comment]
Jokes aside, I've been mounting sysroot by hand since last summer and just today I thought that I'm kinda tired of this.
Problem solved, thanks for your help
